### ISSUE TITLE
Should use aliases instead of duplicate files in .framework

### ISSUE THREAD

**Issue by NSProgrammer** [Buglife/Buglife-iOS#10]
Instead of having duplicate headers and binary throughout the .framework, a single binary and set of headers under .framework/Versions/A would suffice and then .framework/Versions/Current would alias to .framework/Versions/A, .framework/Headers would alias to .framework/Versions/A/Headers, .framework/Modules would alias to .framework/Versions/A/Modules, and .framework/Buglife would alias to .framework/Versions/A/Buglife.  This would cut the size of the framework by one third (66%).

**Comment by schukin** [comment]
Thanks Nolan! Those definitely should be aliases instead of duplicates. We'll be sure to get that fixed in our next SDK release :)

**Comment by schukin** [comment]
Forgot to mention, this was fixed in our last release. Thanks again @NSProgrammer!
