### ISSUE TITLE
Warning: Conflicting Nullability Specifier on Return Types

### ISSUE THREAD

**Issue by merktassel** [Buglife/Buglife-iOS#16]
Since migrating to Swift 3, we've been getting the following warning:  `/our-app/Pods/Buglife/Buglife.framework/Headers/Buglife.h:186:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'`. We're using the latest version (1.3.1) of Buglife.

**Truncated AppDelegate.swift**

```
...

import Buglife

@UIApplicationMain
class AppDelegate: ..., BuglifeDelegate {

    ...

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        ...

        // Setup Bug Reporting
        Buglife.shared().start(withAPIKey: "xxx")
        Buglife.shared().invocationOptions = [.floatingButton]
        Buglife.shared().delegate = self

        ...

        // Finish Setup
        return true
    }

...
```

Thus far we haven't noticed any issues with Buglife, but we do have `Treat Warnings as Errors` set to `Yes` in our build settings, which is causing Buglife to throw build errors in our continuous integration cycle.

**Comment by schukin** [comment]
Good catch! Just released Buglife 1.3.2, which fixes this issue.
