### ISSUE TITLE
Ability to turn off "Thanks for filing a bug report?"

### ISSUE THREAD

**Issue by ekimia** [Buglife/Buglife-iOS#19]
.. or customizing the message.

**Comment by schukin** [comment]
Totally! We'll add this to our next release, which goes out tomorrow.

**Comment by schukin** [comment]
Buglife v1.5.1 is out! You can now disable this dialog by implementing the following delegate method:

https://github.com/Buglife/Buglife-iOS/blob/master/Buglife.framework/Versions/A/Headers/Buglife.h#L235

Thanks for the suggestion, and keep 'em coming :)
