### ISSUE TITLE
feature request: able to customize text or i18n all text

### ISSUE THREAD

**Issue by sbhhbs** [Buglife/Buglife-iOS#2]

**Comment by schukin** [comment]
We're working on it, stay tuned!

**Comment by schukin** [comment]
Hi @sbhhbs - Buglife v1.1.1 now includes support for German, French, Spanish, and Dutch, as well as APIs to customize many strings (check our [docs](https://www.buglife.com/docs) for more info).

We have more languages planned, but are there any in particular you're looking for? Or any other text you'd like to customize?
