### ISSUE TITLE
Programmatically add fields to a bug report

### ISSUE THREAD

**Issue by ekimia** [Buglife/Buglife-iOS#20]
I know you can make an attachment and tag it along, but it would be incredibly useful to add custom fields, or just 1 if adding multiple would be hard, to a bug report. Then have that information get passed along to the current integrations as well.

**Comment by schukin** [comment]
It just so happens we're already working on this :)
(And until our next release is out, don't forget you can enable QA mode from the Buglife dashboard to add a few additional preconfigured fields. Though we know this isn't enough, which is why we're adding field customization!)

**Comment by ekimia** [comment]
amazing!

**Comment by schukin** [comment]
Apologies, this took a bit longer than expected, but... It's live! https://www.buglife.com/docs/ios/custom-fields.html

All collected data is also passed along to your 3rd-party integrations. We also provide custom field mapping for certain integrations (i.e. Zendesk)... If this is something you're interested in, please let us know which integration you're using and we'll be happy to add support.
