### ISSUE TITLE
Crash when attempting to rotate arrow

### ISSUE THREAD

**Issue by leah** [Buglife/Buglife-iOS#21]
I've noticed our app occasionally crashing when using Buglife.

If you take a screenshot, draw an arrow, then attempt to rotate the arrow with two fingers, the app crashes. It looks like the Buglife is trying to create a new arrow?

The error that appears in the simulator is:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM replaceObjectAtIndex:withObject:]: index 9223372036854775807 beyond bounds [0 .. 1]'

Any help with this?

**Comment by schukin** [comment]
Thanks @leah! We've just released Buglife [v1.5.2](https://github.com/Buglife/Buglife-iOS/releases/tag/1.5.2), which fixes this crash (as well as *finally* adds support for rotating annotations). 👌
