### ISSUE TITLE
Will there be any more Framework?

### ISSUE THREAD

**Issue by MKGitHub** [Buglife/Buglife-iOS#25]
Will there be any more Framework?
I.e. from version 2.0.0

I'm not a fan of using that damn CocoaPods or adding a million sources.

**Comment by schukin** [comment]
Mohsan - Yes! We'll add a prebuilt binary asap.

FWIW, Buglife v2.0.0 is nearly identical to v1.9.5, both API- and feature-wise; the only major difference is that it's open source. You can download the v1.9.5 for now, and we'll get a prebuilt binary up for download shortly.

**Comment by schukin** [comment]
Hi @MKGitHub - Looks like we may have forgotten to close this ticket out. We are once again shipping binary frameworks with every release, which you can download from our website: https://www.buglife.com/docs/ios/installation.html

Sorry for the late response; please leave a not if there's anything else we can do!
