### ISSUE TITLE
Add attachement button (iOS) 

### ISSUE THREAD

**Issue by imanzarrabian** [Buglife/Buglife-iOS#31]
Hi 
Do you guys plan to make the add attachement button optional and not only based on the camera roll permission.  
Do you accept pull requests if we implement this small opt in feature ? 
This is how we'd like to use it :
```objective-c
Buglife.shared().makeAddAttachementButtonAvailable = NO; //YES is default value
```

**Comment by danhd123** [comment]
Hi, sure, we accept pull requests. We’d ask that the property be named `allowsAdditionalAttachments` to be more consistent with the rest of the API. Thanks!

**Comment by danhd123** [comment]
That is, we’ll happily implement this ourselves in a few days, but if you’d like to beat us to it, we’ll be happy to accept a PR!

**Comment by imanzarrabian** [comment]
Ha ha! Not sure to have enough time this week but we'll surely try!
