### ISSUE TITLE
Layout margins don't look right on iPad landscape

### ISSUE THREAD

**Issue by nrbrook** [Buglife/Buglife-iOS#35]
Some cells and headers somehow have layout margins set that move the content quite far in, and make things out of line with each other. See screenshot.
![screen shot 2018-04-06 at 12 55 41](https://user-images.githubusercontent.com/1141167/38420338-477fc44c-399b-11e8-81ec-3ca82ed0a533.png)

**Comment by danhd123** [comment]
Fixed in 
https://github.com/Buglife/Buglife-iOS/commit/a6534201e8f01536b0067b6f87eec2ada3c2bdac
