### ISSUE TITLE
Not receiving any bug report emails even though it says successfully sent from the app?

### ISSUE THREAD

**Issue by sibincc** [Buglife/Buglife-iOS#43]
I just implemented buglife to my ios app but not receiving any emails to my mail id. Any help is appreciated.

**Comment by schukin** [comment]
Hi - it looks as though you were attempting to initialize Buglife using `startWithEmail()` with an API key rather than an email. If you have an API key already, please use the `startWithAPIKey()` method.

**Comment by sibincc** [comment]
exactly i just found that myself its working now
