### ISSUE TITLE
Feature: add explanation on first buglife report for user

### ISSUE THREAD

**Issue by philippeauriach** [Buglife/Buglife-iOS#5]
I tested the workflow on someone who did not know that I integrated buglife into the app. He took a screenshot, saw the prompt for submitting a bug, accepted and then could not understand how to add arrows / magnifying glass / pixel vision, so he closed it and did not submit the bug. I imagine that numerous of people not train to bug reporting tools would not go through all the process. An explanation prompt on the first time the view is opened would help them fill bug reports.

**Comment by schukin** [comment]
Thanks @philippeauriach! We absolutely think we need better user education, and it's something we're working on for an upcoming release.
