### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [Buglife/Buglife-iOS#6]
It's will be great to add [Carthage](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started) support
You can follow this tutorial: [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)

**Comment by schukin** [comment]
Thanks for the link! We'll be adding Carthage support soon. :)

**Comment by msanders** [comment]
FWIW, looks like the easiest way to support this for binary-only libraries is by attaching to a [GitHub Release](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file).

**Comment by schukin** [comment]
Thanks @msanders! We're still working on this, however we're hitting some speed bumps w/ Carthage & binary libraries. Our latest issue has been posted here:

https://github.com/Carthage/Carthage/issues/1516

**Comment by schukin** [comment]
Looks like this is back on us.

To recap: Buglife-iOS is currently shipped as a static ("fake") framework, thus won't work with Carthage. We'll need to make some structural changes in order to ship a true framework; Re-opening this ticket.

**Comment by danhd123** [comment]
Hi @msanders and @TofPlay, thanks for your patience. Buglife is now open source, and has Carthage support. Enjoy!
