### ISSUE TITLE
bug: statusBar rotate in landscape though restricted using FloatingButton

### ISSUE THREAD

**Issue by patBurger** [Buglife/Buglife-iOS#8]
Hi guys, found a litte bug. 
StatusBar rotates in landscape while using LIFEInvocationOptions.FloatingButton and rotating device to landscape although UIInterfaceOrientation is restricted to portrait by overriding **func supportedInterfaceOrientations() -> UIInterfaceOrientationMask**. The topViewController stays in portrait.
I have to override the method because 2 viewController should allow landscape.

Settings in Info.plist -> Deployment Info -> Device Orientation 
[x] Portrait
[ ] Upside Down
[x] Landscape Left
[x] Landscape Right

Thanks for your super cool tool!

**Comment by schukin** [comment]
Thanks for letting us know! And good news - we released Buglife v1.0.2 today, which includes a fix for this exact issue :sunglasses:
