### ISSUE TITLE
Works good with iPhone 6s simulator (iOS 9.2), but not works with iPhone 6 (iOS 8.4.1)

### ISSUE THREAD

**Issue by milan-manwar** [Buglife/Buglife-iOS#9]
I've integrated Buglife using Cocoapods. It works well with iPhone 6s simulator, but not working with my iPhone 6.

Any resolution to this issue?

**Comment by schukin** [comment]
At the moment, Buglife only runs on iOS 9+. The SDK will still build with apps targeting iOS 8 or earlier, but Buglife will log a warning.
